# Generated by Django 5.2.1 on 2025-05-24 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="category",
        ),
        migrations.AddField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("colour", "Colour"), ("size", "Size")],
                default=django.utils.timezone.now,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
