# Generated by Django 5.2.1 on 2025-05-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("store", "0003_remove_variation_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartiteam",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
