# Generated by Django 5.2.1 on 2025-05-24 16:22

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", accounts.models.MYAccountManager()),
            ],
        ),
    ]
