# Generated by Django 5.2.2 on 2025-06-07 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pictue',
            field=models.ImageField(blank=True, null=True, upload_to='photos/accounts'),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
